SELECT USER FROM DUAL;


CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) NOT NULL,
    password VARCHAR2(100) NOT NULL,
    role VARCHAR2(20) DEFAULT 'USER' NOT NULL,
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,

    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT chk_users_role
        CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT chk_users_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE rooms (
    room_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    room_name VARCHAR2(100) NOT NULL,
    capacity NUMBER NOT NULL,
    location VARCHAR2(150),
    description VARCHAR2(500),
    status VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL,

    CONSTRAINT pk_rooms PRIMARY KEY (room_id),
    CONSTRAINT chk_rooms_capacity CHECK (capacity > 0),
    CONSTRAINT chk_rooms_status
        CHECK (status IN ('AVAILABLE', 'MAINTENANCE', 'INACTIVE'))
);

CREATE TABLE resources (
    resource_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    resource_name VARCHAR2(100) NOT NULL,
    resource_type VARCHAR2(100),
    quantity NUMBER DEFAULT 1 NOT NULL,
    status VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL,

    CONSTRAINT pk_resources PRIMARY KEY (resource_id),
    CONSTRAINT chk_resources_quantity CHECK (quantity > 0),
    CONSTRAINT chk_resources_status
        CHECK (status IN ('AVAILABLE', 'MAINTENANCE', 'INACTIVE'))
);

CREATE TABLE bookings (
    booking_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    room_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    attendee_count NUMBER NOT NULL,
    purpose VARCHAR2(500),
    status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_bookings PRIMARY KEY (booking_id),

    CONSTRAINT fk_bookings_room
        FOREIGN KEY (room_id)
        REFERENCES rooms(room_id),

    CONSTRAINT fk_bookings_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id),

    CONSTRAINT chk_bookings_time
        CHECK (end_time > start_time),

    CONSTRAINT chk_bookings_attendees
        CHECK (attendee_count > 0),

    CONSTRAINT chk_bookings_status
        CHECK (
            status IN (
                'PENDING',
                'CONFIRMED',
                'REJECTED',
                'CANCELLED',
                'EXPIRED',
                'COMPLETED'
            )
        )
);

CREATE TABLE booking_resources (
    booking_id NUMBER NOT NULL,
    resource_id NUMBER NOT NULL,
    quantity NUMBER NOT NULL,

    CONSTRAINT pk_booking_resources
        PRIMARY KEY (booking_id, resource_id),

    CONSTRAINT fk_br_booking
        FOREIGN KEY (booking_id)
        REFERENCES bookings(booking_id),

    CONSTRAINT fk_br_resource
        FOREIGN KEY (resource_id)
        REFERENCES resources(resource_id),

    CONSTRAINT chk_br_quantity
        CHECK (quantity > 0)
);

CREATE TABLE notifications (
    notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER NOT NULL,
    message VARCHAR2(500) NOT NULL,
    type VARCHAR2(50),
    is_read CHAR(1) DEFAULT 'N' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_notifications
        PRIMARY KEY (notification_id),

    CONSTRAINT fk_notifications_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id),

    CONSTRAINT chk_notifications_read
        CHECK (is_read IN ('Y', 'N'))
);


SELECT table_name
FROM user_tables
ORDER BY table_name;



INSERT INTO users
(name, email, password, role, status)
VALUES
('System Admin', 'admin@event.com', 'admin123', 'ADMIN', 'ACTIVE');

INSERT INTO users
(name, email, password, role, status)
VALUES
('Rahul Sharma', 'rahul@event.com', 'rahul123', 'USER', 'ACTIVE');

INSERT INTO users
(name, email, password, role, status)
VALUES
('Priya Singh', 'priya@event.com', 'priya123', 'USER', 'ACTIVE');

INSERT INTO users
(name, email, password, role, status)
VALUES
('Amit Kumar', 'amit@event.com', 'amit123', 'USER', 'ACTIVE');

SELECT COUNT(*) AS USER_COUNT
FROM users;


INSERT INTO rooms
(room_name, capacity, location, description, status)
VALUES
('Conference Room A', 10, 'First Floor',
 'Small conference room with projector', 'AVAILABLE');

INSERT INTO rooms
(room_name, capacity, location, description, status)
VALUES
('Conference Room B', 20, 'First Floor',
 'Medium conference room with video conferencing', 'AVAILABLE');

INSERT INTO rooms
(room_name, capacity, location, description, status)
VALUES
('Training Hall', 50, 'Second Floor',
 'Large hall for training sessions and events', 'AVAILABLE');

INSERT INTO rooms
(room_name, capacity, location, description, status)
VALUES
('Meeting Room C', 6, 'Ground Floor',
 'Small meeting room for discussions', 'AVAILABLE');

INSERT INTO rooms
(room_name, capacity, location, description, status)
VALUES
('Seminar Hall', 100, 'Third Floor',
 'Large seminar hall for presentations', 'AVAILABLE');
 
 
 
 INSERT INTO resources
(resource_name, resource_type, quantity, status)
VALUES
('Projector', 'Display Equipment', 3, 'AVAILABLE');

INSERT INTO resources
(resource_name, resource_type, quantity, status)
VALUES
('Microphone', 'Audio Equipment', 5, 'AVAILABLE');

INSERT INTO resources
(resource_name, resource_type, quantity, status)
VALUES
('Speaker', 'Audio Equipment', 3, 'AVAILABLE');

INSERT INTO resources
(resource_name, resource_type, quantity, status)
VALUES
('Laptop', 'Computing Equipment', 5, 'AVAILABLE');

INSERT INTO resources
(resource_name, resource_type, quantity, status)
VALUES
('Whiteboard', 'Meeting Equipment', 4, 'AVAILABLE');


COMMIT;

SELECT * FROM users;

SELECT * FROM rooms;

SELECT * FROM resources;

